version: '3.8'

services:
  db:
    image: mariadb:10.11
    container_name: firefly_db
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword  # Change this in production
      - MYSQL_DATABASE=firefly
      - MYSQL_USER=firefly
      - MYSQL_PASSWORD=firefly            # Change this in production
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - firefly_network
    
  app:
    image: yourname/firefly-iii-rootless:latest  # Replace with your Docker Hub username
    container_name: firefly_app
    volumes:
      - firefly_upload:/var/www/html/storage/upload
    ports:
      - '8080:8080'
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_CONNECTION=mysql
      - DB_DATABASE=firefly
      - DB_USERNAME=firefly
      - DB_PASSWORD=firefly            # Change this in production
      - APP_KEY=CHANGEME_32_CHARS      # Change this to a secure 32 character key
      - APP_URL=http://localhost:8080
      - TZ=Europe/Madrid               # Adjust to your timezone
      - TRUSTED_PROXIES=**             # Adjust according to your proxy configuration
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - firefly_network

networks:
  firefly_network:
    driver: bridge

volumes:
  db_data:
    driver: local
  firefly_upload:
    driver: local
