name: Docker Build and Push

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * 0'  # Run every Sunday at 2:00 UTC

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Make script executable
        run: chmod +x rootless-init.sh
        
      - name: Get Firefly III version
        id: firefly_version
        run: |
          LATEST_VERSION=$(curl -s https://api.github.com/repos/firefly-iii/firefly-iii/releases/latest | grep -Po '"tag_name": "\K.*?(?=")')
          echo "FIREFLY_VERSION=${LATEST_VERSION}" >> $GITHUB_ENV
          echo "firefly_version=${LATEST_VERSION}" >> $GITHUB_OUTPUT
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/firefly-iii-rootless:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/firefly-iii-rootless:${{ steps.firefly_version.outputs.firefly_version }}
          build-args: |
            PUID=1000
            PGID=1000